name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    env:
      platform: linux
      region: eastus

      user: ${{ secrets.USER }}
      password: ${{ secrets.PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: imprimir mensaje
        run: echo holaaaaa
      - name: imprimir variables
        run: |
          echo Plataforma: $platform
          echo Region: $region
          echo Usuario: $user
          echo Contraseña: $password

      - name: imprimir variables
        if: ${{ env.platform == 'windows' }}
        run: |
          echo Plataforma: ${{ env.platform }}
          echo Region: ${{ env.region }}

      - name: Verificar usuario
        if: ${{ env.user != '' && env.password != '' }}
        run: |
          echo "Usuario y contraseña correctos"

      - name: Mostrar variables por defecto
        run: |
          echo Actor: ${{ github.actor }}
          echo repositorio: $GITHUB_REPOSITORY
          echo "Event: ${{ toJson(github.event) }}"
